class TaskErrors(Exception):
    pass


class TaskNotFound(TaskErrors):
    pass
